apiVersion: apps/v1
kind: Deployment
metadata:
  name: lottery-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: lottery-server
    spec:
      containers:
        - name: lottery-server
          image: lottery-server:v0.0.1
          imagePullPolicy: IfNotPresent
          ports:
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
spec:
  type: NodePort
  selector:
    app: lottery-server
  ports:
  - name: lott-server-listen
    port: 7070
    targetPort: 8080
    nodeport: 6060